apiVersion: v1
kind: Service
metadata:
  name: dadjokes
  namespace: namespace-workflow-1741603522260
  labels:
    app.kubernetes.io/name: dadjokes
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dadjokes
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000